services:
  db:
    image: postgres:14
    restart: always
    container_name: book-service-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/db-migration.sql:/docker-entrypoint-initdb.d/init.sql


